pipeline:
  test:
    image: python
    commands:
      - pwd
      - ls
      - python uploadPic/uploadPic_test.py

  publishTest:
    image: python
    commands:
      - echo Running publish steps

